language: cpp
compiler:
  - clang
  - gcc
script:
  - cmake .
  - make
  - src/vsssrv -v
  - src/vsscli -v
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - gcc-4.9
      - g++-4.9
      - clang-3.5
