language: cpp
compiler:
  - clang
  - gcc
script:
  - cmake .
  - make
  - src/vsssrv -v
  - src/vsscli -v
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - gcc-8.0
      - g++-8.0
      - clang-8.0
